version: "3.9"

services:
  db:
    image: postgres:16
    container_name: meetingai-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: meeting_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d meeting_ai"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
